name: Github build

on: 
  push:
    branches:
     - dev


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14']
    name: Node ${{ matrix.node }}

    # env:
    #   php-ini-values: post_max_size=256M
    #   wp-bp-directory: src/wp-content/plugins/buddypress
    #   DB_DATABASE: db_test
    #   DB_USER: root
    #   DB_PASSWORD: 'root'
    #   DB_HOST: localhost

    steps:
      # - run: |
      #     sudo /etc/init.d/mysql start
      #     mysql -e 'CREATE DATABASE db_test;' -uroot -proot
      #     mysql -e 'SHOW DATABASES;' -uroot -proot
      - uses: actions/checkout@v2
      - name: Setup node js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: ls -al ./node_modules
      - run: npm install -g npm@9
      - run: npm install
      - run: ls -al ./node_modules

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ./node_modules

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - run: ls -al ./
      - uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: ./node_modules
      - run: ls -al ./
      - name: Display structure of downloaded files
        run: ls -R ./node_modules